# Generated by Django 4.0.1 on 2022-01-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='decimal',
            new_name='decimals',
        ),
    ]
